app:
  jwt:
    secret:
    algorithm: HS512
    expire:
      access: 10m
      refresh: 10d


transports:
  http:
    port: 3456

  kafka:
    id: social-network
    replication: 1
    brokers: 127.0.0.1:19092
    migration:
      version: 1668102929637-n488avov-create-posts-topic

logger:
  levels:
    any: debug
  prettry: true
  sentry:
    dsn:

resources:
  postgres:
    host: 127.0.0.1
    port: 15432
    db: social_networks
    user: user
    password: user

  mailjet:
    public:
    private:

  s3:
    host:
    accessKeyId:
    secretAccessKey:
    bucket:

  redis:
    host: 127.0.0.1
    port: 16379
    db: 0

  mongo:
    hosts: 127.0.0.1:17017,127.0.0.1:17018
    rs:
      name: sn
    db: posts
    auth:
      user: sn
      password: password
